//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrollment
    {
        public long StudentId { get; set; }
        public string SemesterId { get; set; }
        public string CourseNum { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
