//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentDB2017Entities : DbContext
    {
        public StudentDB2017Entities()
            : base("name=StudentDB2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseEnrollment> CourseEnrollments { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CoursesCompleted> CoursesCompleteds { get; set; }
        public virtual DbSet<CoursesOffered> CoursesOffereds { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<InstructorRank> InstructorRanks { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
